name: Unit Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      USE_CACHE: false
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Install node packages
        run: pnpm i

      - run: pnpm lint

      - run: pnpm test:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: makerdao/sky-governance-portal
